### ISSUE TITLE
Exection  issue :  Java_org_webrtc_SoftwareVideoEncoderFactory_nativeCreateFactory__) - is the library loaded, e.g. System.loadLibrary? 

### ISSUE THREAD

**Issue by xbaker** [livekit/client-sdk-react-native#112]
Hello

**Describe the bug**
 After installing the last version of react native liveKit : client-sdk-react-native

```
yarn add @livekit/react-native @livekit/react-native-webrtc
```

adding on android Application class

```
@Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      DefaultNewArchitectureEntryPoint.load();
    }
    ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());

      LiveKitReactNative.setup(this, new AudioType.CommunicationAudioType());
}
```

**Packages**
```
"react": "18.2.0",
"react-native": "0.72.3",
"@livekit/react-native": "^1.3.0",
"@livekit/react-native-webrtc": "^114.0.0-beta.0",
```
i got this error:
```
java.lang.UnsatisfiedLinkError: No implementation found for long org.webrtc.SoftwareVideoEncoderFactory.nativeCreateFactory()
 (tried Java_org_webrtc_SoftwareVideoEncoderFactory_nativeCreateFactory and  Java_org_webrtc_SoftwareVideoEncoderFactory_nativeCreateFactory__) - is the library loaded, e.g. System.loadLibrary?
    at org.webrtc.SoftwareVideoEncoderFactory.nativeCreateFactory(Native Method)
    at org.webrtc.SoftwareVideoEncoderFactory.<init>(SoftwareVideoEncoderFactory.java:23)
    at com.livekit.reactnative.video.SimulcastVideoEncoderFactoryWrapper$FallbackFactory.<init>(SimulcastVideoEncoderFactoryWrapper.kt:67)
    at com.livekit.reactnative.video.SimulcastVideoEncoderFactoryWrapper.<init>(SimulcastVideoEncoderFactoryWrapper.kt:237)
    at com.livekit.reactnative.LiveKitReactNative.setup(LiveKitReactNative.kt:24)
```

**Comment by davidliu** [comment]
Version 1.3.0 isn't compatible with `@livekit/react-native-webrtc` version 114.

Use version 1.4.0, which has just been released.
